apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      containers:
      - image: image
        livenessProbe:
          failureThreshold: 1
          httpGet:
            path: /api/healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 3
        name: main
        ports:
        - containerPort: 8080
          name: rest
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /api/healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 50m
            memory: 150Mi
          requests:
            cpu: 5m
            memory: 20Mi
        volumeMounts:
        - mountPath: /go/app/config.yaml
          name: configmap
          subPath: config.yaml
      volumes:
      - configMap:
          name: configmap
        name: configmap
