apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hackaton

commonAnnotations:
  team: grupo4

configMapGenerator:
- literals:
  - LOG_LEVEL=info
  name: configmap

resources:
- deployment.yaml
- hpa.yaml
- service.yaml